version: '3'

services:

  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

  app:
    container_name: lavina
    build: .
    ports:
      - "8080:8080"
      - "8081:80"
    depends_on:
      - db

  